Add a rust-toolchain.toml
ascjones/subsee pull request #10
Opened 2022-04-20 02:43 UTC by elliot-midnight

2022-04-21 15:45 UTC, chevdor requested changes
I still don't think we should "stick" too much to the very specific 1.60

2022-04-21 15:45 UTC, chevdor commented on rust-toolchain.toml
> +channel = "1.60"
```suggestion
channel = "stable"
```

2022-04-21 15:46 UTC, chevdor commented
Thank you for taking the time to split your PRs @elliot-midnight

2022-04-24 01:43 UTC, elliot-midnight commented on rust-toolchain.toml
> +channel = "1.60"
Picking a channel seems arbitrary to me. My reasoning is above. Either pin everything or pin nothing. Cargo can solve for version constraints perfectly well in the absence of a lock file. Even without a lock file, the versions in the `Cargo.toml` file limit what can happen. So if you don't like pinning this, I might suggest just deleting the `lock` file as a more consistent direction.

2022-04-26 09:20 UTC, ascjones commented
I am archiving this repo now since the [`subxt-cli`](https://github.com/paritytech/subxt#downloading-metadata-from-a-substrate-node) now has the same functionality and is maintained properly.

2022-04-26 09:20 UTC, closed without merging